services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/idolTracker
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongodb/mongodb-community-server:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    # environment:
    #   - MONGODB_INITDB_ROOT_USERNAME=admin
    #   - MONGODB_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    restart: unless-stopped

volumes:
  mongo-data:

