services:
  # backend:
  #   build: .
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./app:/code/app
  #   environment:
  #     - MONGO_URI=mongodb://admin:${MONGO_ROOT_PASSWORD}@mongo:27017/idolTracker?authSource=admin
  #     - OPENAI_API_KEY=${OPENAI_API_KEY}
  #     - FRONTEND_PORT=${FRONTEND_PORT}
  #   depends_on:
  #     - mongo
  mongo:
    image: mongodb/mongodb-community-server:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    # environment:
    #   - MONGODB_INITDB_ROOT_USERNAME=admin
    #   - MONGODB_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    restart: unless-stopped

volumes:
  mongo-data:

